### ISSUE TITLE
Non-obvious name, difficult to search for

### ISSUE THREAD

**Issue by evancz** [NoRedInk/elm-decode-pipeline#10]
I just tried to point someone here in [this thread](https://www.reddit.com/r/elm/comments/4ulle5/needing_to_decode_large_json_structures/), but I could not find the package.

Searching for "json" produced nothing on http://package.elm-lang.org/, so I think it'd be worth considering:
- Giving this package a more obvious name, like `elm-json`.
- Including the term "JSON" in the description in `elm-package.json`.

**Comment by rtfeldman** [comment]
Added to description in bcb83ebe6f99520bebf9c4a8fdaaa46dca0ba25b. 

I think renaming just for that would be too disruptive, considering how many people use this package.
