### ISSUE TITLE
Decode JSON inside a JSON object

### ISSUE THREAD

**Issue by joshhornby** [NoRedInk/elm-decode-pipeline#24]
Hi, is it possible to decode JSON inside another JSON object? For example

```
exampleDecoder : Decoder Person
exampleDecoder =
    decode Person
        |> required "name" string
        |> required "age" string
        |> required "moreJson" string -- This is a JSON string
```

In the example above I'd like to access the data inside the `moreJson` property.

Thanks

**Comment by jxxcarlson** [comment]
I have the same problem. Here is a sample JSON object:
```
{"status":"success","document":{"id":255, "title":"Foo", 
         "text": "This *is* a test",  "rendered_text": "This <b>is</b> a test."}
```
I need to extract the contents of the documents field and decode it `Document`:
```
type alias Document =
  { id : String
  , title : String
  , text : String
  , renderedText: String
  }
```
I already have this decoder:
```
documentDecoder : Decoder Document
documentDecoder =
    decode buildDocument
        |> required "id" string
        |> required "title" string
        |> required "text" string
        |> required "rendered_text" string


buildDocument : String -> String -> String -> String -> Document
buildDocument id title text rendered_text =
```

**Comment by joshhornby** [comment]
@jxxcarlson In order to answer my own issue take a look at https://gist.github.com/joshhornby/50fef6aa18d8d908ddab5574f133f27e#file-app-elm-L27

Hopefully this will help clear up what you need to do - Bear in mind there might be a nicer/cleaner syntax to reduce some boilerplate, still learning Elm!

**Comment by pietro909** [comment]
hi @joshhornby thanks for your snippet.
I still would like to get rid of the intermediate `Model` type alias:
```elm

type alias SearchResult =
  { id: String
  , title: String
  , thumbnailUrl: String
  }

buildVideo : Decoder SearchResult
buildVideo =
  decode SearchResult
    |> requiredAt ["id", "videoId"] string
    |> requiredAt ["snippet", "title"] string
    |> requiredAt ["snippet", "thumbnails", "high", "url"] string

type alias Model =
  { items: List SearchResult }

decodeVideos : Decoder Model
decodeVideos =
  decode Model
    |> required "items" (list buildVideo)
```

I would like to be able to write it this way:

```elm
decodeVideos : Decoder (List SearchResult)
decodeVideos =
  decode (List SearchResult)
    |> required "items" (list buildVideo)
```

But it complains that `List` is not found. Does someone know how to write it properly?

Thanks

**Comment by subwaycinema** [comment]
@pietro909, in your specific example, if you fall back to `Json.Decode` for the "outer" JSON (still using `Json.Decode.Pipeline` for the "inner" JSON), you can delete the second `type alias`.

    import Json.Decode as Decode exposing (Decoder, list)
    ...
    decodeVideos : Decoder (List SearchResult)
    decodeVideos =
        Decode list buildVideo`

**Comment by pietro909** [comment]
Hi @subwaycinema sorry for the late reply: thank you for your suggestion, although the working version is a bit different:

```elm
decodeVideos : Decoder (List SearchResult)
decodeVideos =
  Json.Decode.at [ "items" ]
    (list buildVideo)
```

**Comment by mltsy** [comment]
It doesn't look like anybody here has actually addressed the use case of decoding double-encoded JSON, which is what I read in the original post, unless I'm mistaken (a JSON-encoded string field inside a parent JSON object)?  I have submitted a PR for this use-case to json-extra if you would like an example, or perhaps to comment on it: https://github.com/elm-community/json-extra/pull/12

**Comment by rtfeldman** [comment]
This is a good question! I'm going to close the issue, since it's not specific to decode-pipeline, but hopefully these answers have been helpful!
