### ISSUE TITLE
Code example in Elm package description is out of date

### ISSUE THREAD

**Issue by ialexryan** [NoRedInk/elm-decode-pipeline#29]
Hi there! Thanks for making this cool-looking package.

The [code example](http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest#examples) on the description of this package on elm's website is out of date; specifically it seems to be commit 16be54b91544410f7527b7afcdc597d85f30a241, which introduced a breaking bug in the example code that was fixed in #21/#23.

The end result is that the example code on that page won't run; considering that page is linked to in [the very first page of the official Elm guide](https://guide.elm-lang.org/install.html#elm-package) I think it would be nice to fix that. Is that possible?

**Comment by ryan-senn** [comment]
To add to this, most example use `import Decode.Pipeline exposing (decode, required)` instead of `import Json.Decode.Pipeline exposing (decode, required)`. Note the missing `Json` in the import.

**Comment by ialexryan** [comment]
@rtfeldman thoughts? I think I've already diagnosed the issue in detail and this should hopefully be a quick fix that would save a lot of new Elm users from getting confused! Thanks for your time.

**Comment by rtfeldman** [comment]
Fixed on `master`, and should be updated in the next release!
