### ISSUE TITLE
Idea: `nullable`

### ISSUE THREAD

**Issue by rtfeldman** [NoRedInk/elm-decode-pipeline#3]
A common desire is to have a field that can be `null`, and which gets decoded into a `Maybe`.

Currently we do this with `maybeNull` from elm-decode-extra. What if we could do this instead?

``` elm
required : String -> Decoder a -> Decoder (a -> b) -> Decoder b
nullable : String -> Decoder a -> Decoder (a -> b) -> Decoder (Maybe b)

type alias User =
  { id : Int
  , email : Maybe String
  , name : String
  , percentExcited : Float
  }


userDecoder : Decoder User
userDecoder =
  decode User
    |> required "id" int
    |> nullable "email" string
    |> optional "name" string "(fallback if name not provided)"
    |> hardcoded 1.0
```

**Comment by eeue56** [comment]
`nullable` and `optional` are already pretty easy to confuse conceptionally - now they're confusing with the names :)

**Comment by rtfeldman** [comment]
So I actually like that about this - then the docs for each can explain the difference and link to the other one.

I feel like right now the potential for confusion is still there, but it's not clear what you're supposed to do if you want a field that must be present but might be `null`.

**Comment by eeue56** [comment]
What about when something is optional and nullable?

**Comment by rtfeldman** [comment]
Then that API is bad and whoever wrote it should feel bad. 😜 

Jokes aside, that seems to be a rare case in practice (don't know if it's even come up for us yet), whereas either of the others seem to be pretty common.

**Comment by lorenzo** [comment]
I've seen the need for `nullable` in many different API, so I think it would be a nice to have.

**Comment by ThomasWeiser** [comment]
Yes, there should be such a function! Was going for a PR myself before I've seen Richard already suggests it here.

The name `nullable` suggest that the function does explicitly test for `null`.

I would also suggest a function `maybe`, corresponding to `Json.Decode.maybe`: Always succeed and return a `Just value` if the given decoder succeeds and `Nothing` if it fails or if the key doesn't exist.

**Comment by rtfeldman** [comment]
@lorenzo - curious, how do you handle those cases today?

**Comment by rtfeldman** [comment]
@ThomasWeiser I thought about that, but if something fails to decode, it suggests some code is broken somewhere (perhaps the API did something wrong, or the decoder is written against the wrong API) but succeeding with `Nothing` would sweep that under the rug!

Obviously sometimes that's exactly what you want, but I think you should have to go out of your way to "sweep the error under the rug," and putting a convenient rug-sweeper in the public API would make it easier to write less maintainable code long-term. 😄

**Comment by ThomasWeiser** [comment]
@rtfeldman Fair point

**Comment by lorenzo** [comment]
I'm using `Json.Decode.maybe` for those cases @rtfeldman

**Comment by ThomasWeiser** [comment]
In my application at hand I actually want a Maybe for a maybe missing key. Currently I have to write:

``` elm
Json.Decode.Pipeline.optional "name" (Json.Decode.map Just Json.Decode.string) Nothing
```

So I suggest to have these two functions in `Json.Decode.Pipeline`, both returning a `Maybe`:
1. `maybeNull`
2. `maybeMissing`
(modulo naming preferences)

**Comment by lukewestby** [comment]
I would love to have this function! I think setting empty fields to null instead of leaving them off is easier to debug. It's easier to see which things are null rather than which are missing/present

**Comment by polux** [comment]
Yes that would be useful to me.

**Comment by rtfeldman** [comment]
@ThomasWeiser curious - how often do you find yourself doing that? I've only wanted it once so far.

**Comment by ThomasWeiser** [comment]
> curious - how often do you find yourself doing that? I've only wanted it once so far.

I use Firebase in several of my Elm apps.

Data read from Firebase never uses `null`. Setting a value to `null` actually removes the key.
So, for Firebase data models it's quite common to test for the existence of a key/value. And most commonly you want to decode that into a `Maybe`.

Also, in greater JS land (according to my feelings) it's not unusual to use the absence of a key to express a meaning. Surely, using `null` here would be nicer, but existing APIs may have a different view.

**Comment by polux** [comment]
Firebase is actually also the reason why I need it :)

**Comment by rtfeldman** [comment]
Ahh okay, that makes sense.

I've opened #5 as a proposal to handle all four combinations. I'm going to close this in favor of that, but if we end up back at "only `nullable`", I'll reopen this.

**Comment by ThomasWeiser** [comment]
> I've opened #4 as a proposal to handle all four combinations. 

I think you mean #5
