### ISSUE TITLE
dealing with list & complex example

### ISSUE THREAD

**Issue by Grummfy** [NoRedInk/elm-decode-pipeline#32]
Hello,
In the documentation, there is not example with complex json data structure, here it is:

```
type alias MyStructure =
  {
    "foo": List Bar
  }
type alias Bar =
  {
    "baz": String
  }
```

json
```
{
  "foo": [
    {"baz": "abc"},
    {"baz": "def"},
  ]
}
```

and then we can have substructure, ...

Can you tell me how to dea with it.

thanks

**Comment by Shivakishore14** [comment]
decodeMyStructure : Decoder MyStructure
    decodeMyStructure =
        decode MyStructure
            |> required "foo" (list decodeBar)

    decodeBar : Decoder Bar
    decodeBar = 
        decode Bar 
            |> required "baz" string

This should work
