### ISSUE TITLE
`resolve`: Inconsistent doc vs type

### ISSUE THREAD

**Issue by Janiczek** [NoRedInk/elm-decode-pipeline#33]
http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/3.0.0/Json-Decode-Pipeline#resolve

>  `resolve : Decoder (Decoder a) -> Decoder a`
Convert a `Decoder (Result x a)` into a `Decoder a`. Useful when you want to perform some custom processing just before completing the decoding operation.

So, one of these is right, and I bet it's the type? :)

**Comment by rtfeldman** [comment]
Fixed on `master` and will be out with the next release!

Thanks @Janiczek
