### ISSUE TITLE
`optional`/`optionalAt`: dealing with "malformed" structures

### ISSUE THREAD

**Issue by zwilias** [NoRedInk/elm-decode-pipeline#34]
Both `optional` and `optionalAt` currently error out if the value decoder fails, and use the fallback when either the value does not exist or is `null`.

The specific semantics of "does the value exist" are not totally obvious. Intuitively, I would say "the JSON object has the specified key" describes the intended semantics.

It's probably better to illustrate with an example; so lets imagine a decoder `decode identity |> optional "foo" (maybe int) Nothing`, and running that on a couple of inputs:

Input              | Result         | Expected
-------------------|----------------|----------
`{ "foo": 12 }`    | `Ok (Just 12)` | ✅
`{ "foo": "bar" }` | `Err "..."`    | ✅
`{ "foo": null }`  | `Ok Nothing`   | ✅
`{ "bar": "baz" }` | `Ok Nothing`   | ✅
`{}`               | `Ok Nothing`   | ✅
`null`             | `Ok Nothing`   | ✅
`"hello world!"`   | `Ok Nothing`   | ❌

The last one seems odd - the input isn't an object, so talking about the existence of a value does not make sense. The `null` case seems in line with the behaviour of decoding the value itself works. 

Having the wrong structure in the underlying JSON value (i.e. anything but `null` or an object) seems like it should also be rejected. Thoughts?

**Comment by jinjor** [comment]
@zwilias 
I did some experiments with the core decoder's `maybe` with some undocumented examples.

http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode#maybe

```elm
json = """{ "name": "tom", "age": 42 }"""

decodeString (maybe (field "age"    int  )) json        -- Ok (Just 42)
decodeString (maybe (field "name"   int  )) json        -- Ok Nothing
decodeString (maybe (field "height" float)) json        -- Ok Nothing
decodeString (maybe (field "height" float)) "null"      -- Ok Nothing
decodeString (maybe (field "height" float)) "\"hello\"" -- Ok Nothing ------ (A)
decodeString (maybe (field "height" float)) ""          -- Err ...

decodeString (field "age"    (maybe int  )) json        -- Ok (Just 42)
decodeString (field "name"   (maybe int  )) json        -- Ok Nothing
decodeString (field "height" (maybe float)) json        -- Err ...
decodeString (field "height" (maybe float)) "null"      -- Err ...
decodeString (field "height" (maybe float)) "\"hello\"" -- Err ... --------- (B)
decodeString (field "height" (maybe float)) ""          -- Err ...
```

What I got to know here is that the `(A)` decoder does not expect the input is an object but `(B)` does. So If we expect `optional` to behave the same as `(A)`, the result you listed above seems no problem.

(My first intuition was the same to yours, btw.)
