### ISSUE TITLE
NAMING ERROR

### ISSUE THREAD

**Issue by victorhazbun** [NoRedInk/elm-decode-pipeline#37]
-- NAMING ERROR ------------------------------------------------------ Bingo.elm

This usage of variable `required` is ambiguous.

101|         |> required "phrase" string
                ^^^^^^^^
Maybe you want one of the following?

    Json.Decode.Pipeline.required
    Html.Attributes.required

Detected errors in 1 module.

elm-live:
  elm-make failed! You can find more info above. Keep calm and take your time
  to fix your code. We’ll try to compile it again as soon as you change a file.

Could you please tell me how to make them work together?

**Comment by victorhazbun** [comment]
### I figured it out! 

Fixed it with an alias "JsonDecodePipeline", this was happening because the `Html` lib also exposes a `required` function.

### Solution: 
```
import Html exposing (..)
import Json.Decode as Decode exposing (int, string, float, Decoder)
import Json.Decode.Pipeline as JsonDecodePipeline exposing (decode, required, optional, hardcoded)
```

**Comment by tesk9** [comment]
I'm glad you figured it out! Closing, as this isn't an issue with the functionality of the library.

**Comment by victorhazbun** [comment]
@tesk9 I know this is not a issue associated to the library, but it will be nice to let users know how to avoid this kind of problems while using the library since it shares function names with the Html library.
