### ISSUE TITLE
Decoding failures do not follow pipeline order

### ISSUE THREAD

**Issue by Qqwy** [NoRedInk/elm-decode-pipeline#41]
`custom` is in essence an implementation of `apply` (to be precise, Haskell's `<**>`).

However, the current implementation of `custom` is slightly wrong. One would expect that the Json Decode Pipeline would give the same answers as the built-in decoding functions if used at the same way. But this is not always the case:

## Example

```elm
module DecodeTest exposing (..)

import Json.Decode.Pipeline exposing (decode, required)
import Json.Decode as Decode exposing (map2, field, fail)


type User
    = User String Int

{-| Decoder using the JSON Decode Pipeline -}
user_decoder : Decode.Decoder User
user_decoder =
    decode User
        |> required "name" failname
        |> required "age" failage


{-| Decoder using only built-in functions -}
user_decoder2 : Decode.Decoder User
user_decoder2 =
    Decode.map2 User
        (field "name" failname)
        (field "age" failage)


failname =
    Decode.fail "I failed at name parsing"


failage =
    Decode.fail "I failed at age parsing"



user_json =
    """
     {"age": 42, "name": "Herbert"}
     """


usertest =
    Decode.decodeString user_decoder user_json


usertest_builtin =
    Decode.decodeString user_decoder2 user_json

```

### Expected Outcome

One would expect `DecodeTest.usertest` and `DecodeTest.usertest_builtin` to return the same outcome.
But this is not what happens!

### Actual Outcome

```
> DecodeTest.usertest
Err "I ran into a `fail` decoder at _.age: I failed at age parsing"
    : Result.Result String DecodeTest.User
```

```
> DecodeTest.usertest_builtin
Err "I ran into a `fail` decoder at _.name: I failed at name parsing"
    : Result.Result String DecodeTest.User
```

The correct implementation, that will evaluate all fields in the same order as the pipeline
(so for `decode a |> field b |> field c |> field d` the result of evaluation will be `a, b, c, d`), looks as follows:

```elm
custom : Decoder a -> Decoder (a -> b) -> Decoder b
custom =
    (flip << Decode.map2) (<|)
```

**Comment by rtfeldman** [comment]
**EDIT:** I just realized I read the examples backward, and thought the proposal was the reverse of what it actually is. 😅

My mistake! 

Yeah, I agree - it should be flipped.
