### ISSUE TITLE
Proposal: Split `optional` into three functions

### ISSUE THREAD

**Issue by rtfeldman** [NoRedInk/elm-decode-pipeline#5]
Based on the discussion in https://github.com/NoRedInk/elm-decode-pipeline/issues/3, it seems like there are common use cases for all four combinations of "field may be missing" and "decode to `Maybe`".

The current approach is to use [`required`](http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/1.1.1/Json-Decode-Pipeline#required) and [`optional`](http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/1.1.1/Json-Decode-Pipeline#optional) and [`Json.Decode.map`](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode#map) and [`Json.Decode.Extra.maybeNull`](http://package.elm-lang.org/packages/circuithub/elm-json-extra/2.2.1/Json-Decode-Extra#maybeNull) to cover these four cases. These come up with varying degrees of regularity for me, but seem to come up [very frequently for others](https://github.com/NoRedInk/elm-decode-pipeline/issues/3).

This proposal would rename the current `optional` to `fallback` (a breaking change, explained below), then introduce a new `optional` and `nullable`, both of which decode to a `Maybe`. The following documentation would be included (or at least linked to) in all four functions, so users can quickly tell which they want.
#### Documentation

---

If you want to decode to a `Maybe`, use `nullable` or `optional` like so:

``` elm
import Json.Decode exposing (Decoder, string)
import Json.Decode.Pipeline exposing (decode, nullable, optional)

type alias User = { email : Maybe String }

{- nullable

    {email: "foo@example.com"} ==> Ok (Just "foo@example.com")
    {email: null}              ==> Ok Nothing
    {}                         ==> Err "Missing field `email`"
-}
emailCanBeNull : Decoder User
emailCanBeNull =
  decode User
    |> nullable "email" string

{- optional

    {email: "foo@example.com"} ==> Ok (Just "foo@example.com")
    {email: null}              ==> Err "Expected `email` to be a string, but was null"
    {}                         ==> Ok Nothing
-}
emailCanBeMissing : Decoder User
emailCanBeMissing =
  decode User
    |> optional "email" string
```

If you do not want to decode to a `Maybe`, use `required` or `fallback` like so:

``` elm
import Json.Decode exposing (Decoder, string)
import Json.Decode.Pipeline exposing (decode, required, fallback)

type alias User = { email : String }

{- required

    {email: "foo@example.com"} ==> Ok "foo@example.com"
    {email: null}              ==> Err "Expected `email` to be a string, but was null"
    {}                         ==> Err "Missing field `email`"
-}
emailMustBePresent : Decoder User
emailMustBePresent =
  decode User
    |> nullable "email" string

{- fallback

    {email: "foo@example.com"} ==> Ok "foo@example.com"
    {email: null}              ==> Err "Expected `email` to be a string, but was null"
    {}                         ==> Ok "missing email!"
-}
emailCanBeMissing : Decoder User
emailCanBeMissing =
  decode User
    |> fallback "email" string "missing email!"
```

**Comparison:** Results from decoding objects like `{str: "some string"}`, `{str: null}`, and `{}`,
using [`Json.Decode.string`](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode#string) in conjunction with...

| Function | Field missing? | Value is `null`? | Value decodes? |
| --- | --- | --- | --- |
| `required` | `Err` | `Err` | `Ok str` |
| `nullable` | `Err` | `Ok Nothing` | `Ok (Just str)` |
| `optional` | `Ok Nothing` | `Err` | `Ok (Just str)` |
| `fallback` | `Ok fallbackStr` | `Err` | `Ok str` |

---

I think a breaking change is worthwhile here because it seems like if you have a function that decodes a missing field as `Nothing`, and then you call _some other function_ `optional`, that seems unreasonably prone to confusion. If any function is going to decode a missing field to `Nothing`, that function seems to have the best claim to the name `optional`.

The status quo API is smaller, which I generally see as a good thing. However, based on https://github.com/NoRedInk/elm-decode-pipeline/issues/3, the status quo is evidently sufficiently cumbersome that using [`Json.Decode.maybe`](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode#maybe) in ways that swallow errors becomes more appealing. That seems like a sufficiently large red flag to justify expanding the API.

How do people feel about this? Please feel free to 👍 or 👎  this in addition to (or instead of) commenting.

**Comment by eeue56** [comment]
Can you give an example of using fallback, optional and nullable?

**Comment by rtfeldman** [comment]
@eeue56 updated the documentation section to include examples!

**Comment by eeue56** [comment]
seems okay to me

**Comment by ThomasWeiser** [comment]
Would it be possible to replace `fallback` with something like

``` elm
type alias User = { email : String }

decode User
    |> (default "missing email!" optional) "email" string 
```

This way default values could be provided for both cases (missing key, null value).
But I am unsure if this API is possible. Also doesn't look so nice.

Also: I can imagine that in the wild you would want to test for absence as well as for `null`. So, a test for null-or-missing may be handy. Yes, that hints at a questionable API design. But this kind of test wouldn't hurt either (in contrary to blindly using `Json.Decode.maybe`).

**Comment by rtfeldman** [comment]
> I can imagine that in the wild you would want to test for absence as well as for null. So, a test for null-or-missing may be handy.

It's imaginable for sure, but designing for might-be-nice is a quick path to a bloated API. 😉

I'm gonna wait for specific use cases (like Firebase and this proposal!) before seriously considering an addition like that.

**Comment by ThomasWeiser** [comment]
Sure.

If you stick to `fallback` I would suggest to let it handle both a missing key as well as a `null` value. IMHO it looks a bit artificial to provide it for one case but not the other.

**Comment by rtfeldman** [comment]
Really it's not so much artificial as experience-based...if anything, it'd be artificial to treat `null` and missing as equivalent without a compelling use case. 😉 

We know about the Firebase use case, where it's important to decode a missing field to `Nothing` because Firebase doesn't allow `null`. So far we haven't heard of a compelling use case to justify the added complexity of "decodes a missing field OR a `null` as `Nothing`."

Happy to revisit if someone has a compelling case for that, the way you and @polux do with Firebase! 😄

**Comment by avh4** [comment]
I would think that for `optional`, it should produce `Ok Nothing` if the JSON value is null.  That seems to match better what I would expect from the plausible incoming JSON.

**Comment by rtfeldman** [comment]
Interesting - I had not considered the "principle of least astonishment" argument for that case.

Would others be _surprised_ if using `optional` on a `null` field decoded to `Err` instead of `Ok Nothing`? (Feel free to 👍 or 👎 this comment.)

**Comment by ThomasWeiser** [comment]
I don't know if I would be surprised, but I thinks it's reasonable to see `null` as a valid `optional` value.

So, building on @avh4 suggestion, we would have:

| Function | Field missing? | Value is `null`? | Value decodes? |
| --- | --- | --- | --- |
| `required` | `Err` | `Err` | `Ok str` |
| `nullable` | `Err` | `Ok Nothing` | `Ok (Just str)` |
| `optional` | `Ok Nothing` | `Ok Nothing` | `Ok (Just str)` |
| `fallback` | `Ok fallbackStr` | `Err` | `Ok str` |

The definition of `fallback` leaves room for the stricter version of _optional_ to be written as:

``` elm
fallback Nothing (Json.Decode.map Just string) "name"
```

**Comment by rtfeldman** [comment]
Hm, but looking at that table, I now wonder why `fallback` and `optional` have different semantics regarding `null`. It doesn't seem justified.

Reviewing our own internal code that currently uses (the function I'm proposing would be called) `fallback`, it doesn't seem like it would be concerning if `null` were accepted in those places.

So I think if `optional` should accept `null`, then it'd make sense for `fallback` to do the same:

| Function | Field missing? | Value is `null`? | Value decodes? |
| --- | --- | --- | --- |
| `required` | `Err` | `Err` | `Ok str` |
| `nullable` | `Err` | `Ok Nothing` | `Ok (Just str)` |
| `optional` | `Ok Nothing` | `Ok Nothing` | `Ok (Just str)` |
| `fallback` | `Ok fallbackStr` | `Ok fallbackStr` | `Ok str` |

This table actually tells a pretty neat story. Each version successfully decodes as many or strictly more possible values than the previous version, and the last version is a convenience function that resolves the previous version's `Maybe` for you.

It's now significantly more work to get at the currently-released implementation of `optional`, but I'm not sure that matters. Would anyone care if only `required` decoded `null` into an `Err`, and all the others decoded `null` into an `Ok` of some sort?

**Comment by ThomasWeiser** [comment]
@rtfeldman LGTM

There is this remaining case, where you want to decode a missing field but reject `null` values. This case is probably too uncommon to justify a dedicated function.

**Comment by rtfeldman** [comment]
Resolution: merged https://github.com/NoRedInk/elm-decode-pipeline/pull/9 and adding `nullable` as a synonym for `Json.Extra.maybeNull` so you can write `required "middleName" (nullable string)` and `optional` just works the way people seem to largely expect it to: decoding `null` using the fallback.
