### ISSUE TITLE
Example in docs for `custom` has missing argument to `Json.Decode.at`

### ISSUE THREAD

**Issue by alex-lew** [NoRedInk/elm-decode-pipeline#8]
The documentation for the `custom` function provides the following snippet of code as an example:

``` haskell
    userDecoder : Decoder User
    userDecoder =
      decode User
        |> required "id" int
        |> custom (at [ "profile", "name" ])
        |> required "email" string
```

Shouldn't that be `custom (at ["profile", "name"] string)`? If I understand correctly, `custom`'s first argument should be a decoder, not a `Decoder a -> Decoder a` function.

Thanks!

**Comment by rtfeldman** [comment]
Yep! Fixed in a518dc0fcd05c7ccc139dfc90d7b48c033363197

Thanks @alex-lew!
